export const IS_DEV=true
export const DEV_URL='https://backend.ggslatam.gg'
//'http://localhost:4000'
//'http://3.22.112.13'
export const PROD_URL='http://localhost:4000'
export const LIVE_EVENT='LiveEvent'
export const MINECRAFT='Minecraft'
export const STATIC_CHALLENGE='StaticChallenge'
export const TOURNAMENTS='Tournaments'
export const SPECIAL_EVENT='normalEvents'
export const INPUT_ERR_MSG_PARTICIPATION='Debes ingresar tu nombre de usuario y/o captura de pantalla'
