import styles from '../styles/Home.module.css';
import Footer from '../components/Footer/Footer.js';
import Header from '../components/Header/Header.js';

export default function Login() {
    return(
      <div style={{ backgroundColor:'#1b0020'}}>
      <Header />
        <div className={styles.mainAbout} >
        <img src="logo.png" className={styles.logoAbout} alt="" />
          <div className={styles.headingAbout}>Términos y condiciones:</div>
<div className={styles.pAbout}> GGs Latam es un sitio creado para los amantes a los Videojuegos. Con eventos diarios y semanales con premios en dinero, el usuario podrá acceder para competir con otros jugadores y retarse en distintas modalidades. Con juegos como Minecraft, Free Fire, Call of Duty Mobile, y Brawl Stars entre otros, el usuario tiene la posibilidad de participar y ser quien se lleve el gran premio. </div>

<div className={styles.headingAbout}>OBJETO</div>
<div className={styles.pAbout}> Los presentes términos y condiciones regulan la autorización de uso que otorga el Proveedor a los usuarios, para que éstos ingresen a la plataforma virtual, y participen en actividades que principalmente constan de retos en videojuegos online con premios en dinero real para clasificados y ganadores de cada actividad. El Proveedor a través de la Plataforma realiza las siguientes acciones: i) exhibe diferentes actividades con premios en dinero real, ii) administra las actividades de cada usuario verificando resultados, y asegurando la sana competencia e integridad de cada participante. PLATAFORMA TECNOLÓGICA QUE PERMITE SU USO Es una plataforma que permite su uso gratuito por varios medios, a saber: i) portal web: www.ggslatam.gg. Los usuarios podrán utilizar La Plataforma exclusivamente para su uso personal y entretenimiento, sin que esto implique el otorgamiento de una licencia de la tecnología de la plataforma de ningún tipo.</div>

<div className={styles.headingAbout}>MODIFICACIÓN</div>
<div className={styles.pAbout}> El Proveedor podrá modificar autónomamente y en cualquier momento en aspectos formales, procedimentales o sustanciales los presentes Términos y Condiciones de uso de La Plataforma, los cuales serán actualizados y puestos a disposición de los usuarios en La Plataforma, siendo la última versión publicada la que regulará las relaciones comerciales que se generen al momento de realizarse la transacción. Así mismo, cuenta con plena autonomía para modificar los usos de La Plataforma permitidos a los usuarios, con el único deber de informarlo por un medio virtual que permita su publicación y comunicación al público.</div>

<div className={styles.headingAbout}>DETALLE DEL SERVICIO</div>
USUARIO
<div className={styles.pAbout}> Toda persona natural que, como destinatario final, use La Plataforma para participar por medio de ésta en actividades Gamer que constan principalmente de retos con premios en dinero real para clasificados y ganadores. El uso de la Plataforma lo realiza el usuario como persona capaz, manifestando que, para la celebración de contratos, cuenta con plena capacidad legal para ser sujeto de derechos y obligaciones, calidades que refrenda al momento de generar su registro.</div>

<div className={styles.headingAbout}>CUENTA DE USUARIO</div>
<div className={styles.pAbout}> Los usuarios usan como referencia para su suscripción, un perfil creado dentro de ggslatam, teniendo como condición necesaria la creación de una Cuenta de Usuario, donde se solicitarán datos como nombre, fecha de nacimiento, teléfono, y dirección de correo electrónico. Se encuentra prohibido tener más de una (1) cuenta relacionada a cualquiera de los datos anteriormente mencionados. Esta información se utiliza para la plena identificación de las personas que pretenden inscribirse y participar en actividades Gamer con premios en dinero real. Para el cumplimiento de los presentes términos y condiciones, para la prevención de fraudes, para vincular al usuario con sus respectivas participaciones y en general para los fines definidos en el acápite manejo de información. Los usuarios en caso de tener cuentas en Facebook, Google y Discord, podrán crear su cuenta de usuario con la utilización de las credenciales allí definidas. Podrán los usuarios, además de la información obligatoria y facultativa requerida al momento de la creación de la cuenta, suministrar voluntariamente más datos relacionados con su individualización al momento en que cree su propio Perfil dentro de La Plataforma. El uso de las cuentas es personal e intransferible, por lo cual los usuario no se encuentran facultados para ceder los datos de validación para el acceso a La Plataforma ni el uso de su cuenta a ningún tipo de terceros. El incumplimiento de lo anterior, acarreará la suspensión y bloqueo definitivo de la cuenta (incluye correo electrónico y número de identificación personal). En caso de olvido de los datos de validación o de usurpación de éstos, es obligación del usuario informar al Proveedor a través de la opción “olvidó su contraseña” o a través de comunicación enviada al correo electrónico soporte@ggslatam.gg. Las cuentas de los usuarios serán administradas por el Proveedor o por la persona que éste designe, teniendo plena facultad para la conservación o no de la cuenta, cuando la información suministrada por los usuario no sea veraz, completa o segura; o cuando se presente incumplimiento de las obligaciones de los usuarios. En ningún momento el Operador solicitará al usuario información que NO resulte necesaria para su participación en retos y/o actividades de plataforma. Con la creación de la Cuenta de Usuario, los usuarios están manifestando su voluntad de aceptación expresa e inequívoca de los presentes Términos y Condiciones de uso de La Plataforma. Parágrafo. Autoriza expresamente el usuario al momento de la aceptación de los presentes Términos, el uso de Cookies por parte del Proveedor en toda actividad de uso que realice de la Plataforma.</div>

<div className={styles.headingAbout}>CAPACIDAD</div>
<div className={styles.pAbout}> En virtud de las condiciones de capacidad legal establecidas en el Código Civil Colombiano y de la validez de la manifestación de voluntad a través de medios electrónicos establecida en la ley 527 de 1999, los usuarios al momento de la creación de la Cuenta de Usuario, manifiestan expresamente tener capacidad para celebrar el tipo de transacciones que se pueden realizar usando La Plataforma; y con base en lo prescrito en la ley 1098 de 2006 de la República de Colombia los menores de edad cuentan con capacidad para celebrar éste tipo de transacciones, no obstante el Proveedor deberá: i) Excluir del sistema de información los datos de menores de edad que hayan utilizado La Plataforma; ii) Dar a conocer a las autoridades de cualquier situación, de la que tenga conocimiento, que ponga en peligro la integridad de un menor de edad.</div>

<div className={styles.headingAbout}>DESCRIPCIÓN DEL SERVICIO</div>
<div className={styles.pAbout}> El Proveedor ofrece a través de La Plataforma un espacio para usuarios en el cuales acceden a actividades en videojuegos online que principalmente constan de retos de habilidad en juegos individuales. Cada reto tiene clasificatorios por posición basadas en capturas de pantalla que el usuario sube a la plataforma como prueba de su participación en dicho reto. Un administrador de ggslatam verifica cada captura de pantalla y declara al ganador, publicando las capturas de pantalla de los clasificados como pruebas de su posición y premio. Registro: El Usuario debe crear su cuenta personal en la cual se requerirán los datos personales que permitan su identificación y validación de participación en cada actividad de la plataforma. Una vez completado el registro el Usuario podrá acceder a cada actividad exhibida en la plataforma y esperar a la fecha de finalización para verificar su posición y/o victoria para el reclamo respectivo de premio si da a lugar. Reclamo de premios: De ser ganador, EL PROVEEDOR se comunicará con el usuario desde el correo electrónico soporte@ggslatam.gg con el fin de coordinar el pago. El método disponible de pago es a través de Paypal. Los pagos se realizan semanalmente de Lunes a Viernes, hasta 10 días hábiles después de la fecha de finalización, con el fin de verificar la identidad e integridad de cada participante clasificado y/o ganador de premios.</div>

<div className={styles.headingAbout}>DEBERES DEL USUARIO</div>
<div className={styles.pAbout}> Con la aceptación de los presentes términos El usuario se obliga a: (1) Suministrar información veraz y fidedigna al momento de crear su Cuenta de Usuario; (2) Abstenerse de transferir a terceros los datos de validación (nombre de usuario y contraseña); (3) Abstenerse de utilizar la Plataforma para realizar actos contrarios a la moral, la ley, el orden público y buenas costumbres en contra del Proveedor o de terceros; (4) Informar inmediatamente al Proveedor en caso de olvido o usurpación de los datos de validación; (5) Abstenerse de realizar conductas atentatorias del funcionamiento de La Plataforma, como trampa o ‘hacking’ dentro de videojuegos a participar; (6) Abstenerse de suplantar la identidad de otros usuarios; (7) Abstenerse de descifrar, descompilar o desensamblar cualquier elemento de La Plataforma o de cualquiera de sus partes; (8) Habilitar la utilización de ventanas emergentes durante la operación; (9) En general todas aquellas conductas necesarias para la ejecución del negocio jurídico.</div>

<div className={styles.headingAbout}>DEBERES DEL PROVEEDOR</div>
<div className={styles.pAbout}> En virtud de los presentes términos el Proveedor, se obliga a (1) Suministrar información cierta, fidedigna, suficiente, clara y actualizada respecto de las actividades que ofrece en la plataforma; (2) Informar suficientemente sobre los medios habilitados para que los usuario realicen el pago; (3) Poner a disposición de los usuario los términos y condiciones de uso de La Plataforma de forma actualizada; (4) Utilizar la información únicamente para los fines establecidos en los presentes términos; (5) Disponer y pagar dentro de los plazos establecidos en estos términos y condiciones los premios respectivos a cada ganador de las actividades en la plataforma; (6) Asegurar la sana competencia e integridad de cada participación verificando las respectivas capturas de pantalla de usuarios en la plataforma.</div>

<div className={styles.headingAbout}>CONSIDERACIONES FINALES CONTENIDOS</div> <div className={styles.pAbout}> A través de la Plataforma el Proveedor podrá poner a disposición de los usuarios información de carácter comercial y publicitario, propio o de terceros de conformidad a las buenas costumbres comerciales. En estos casos el Proveedor no avala, garantiza o compromete su responsabilidad frente a los servicios y/o productos que se comercialicen por éstos terceros, ya que la Plataforma sirve como canal de comunicación y publicidad, mas no como herramienta de prestación de servicios. En consecuencia, es total responsabilidad de los usuarios el acceso a los sitios que remite la publicidad, asumiendo la obligación de verificar y conocer los términos de los servicios ofrecidos por los terceros. Toda la información puesta a disposición en la Plataforma como imágenes, publicidad, nombres, marcas, lemas y demás elementos de propiedad intelectual; son utilizados legítimamente por el Proveedor, sea porque son de su propiedad, porque tiene autorización para ponerlos a disposición, o porque se encuentra facultado para hacerlo en virtud de las decisiones 351 de 1993 y 486 de 2000 de la Comunidad Andina de Naciones y la ley 23 de 1982 .</div>

<div className={styles.headingAbout}>FUNCIONAMIENTO DE LA PLATAFORMA</div>
<div className={styles.pAbout}> El Proveedor administra directamente o por medio de terceras personas la Plataforma, toda la información que se comunica allí corresponde a información cierta y actualizada. En ningún caso responderá por daños directos o indirectos que sufra el usuario por la utilización o incapacidad de utilización de La Plataforma. La plataforma se encuentra disponible las 24 horas del día para su acceso y participación en actividades. El Proveedor realiza los mejores esfuerzos para mantener en operación La Plataforma, pero en ningún caso garantiza disponibilidad y continuidad permanente de La Plataforma. El Proveedor se reserva el derecho de cancelar las cuentas de usuarios y/o de prohibir el acceso a La Plataforma a los usuarios que realicen conductas violatorias de los presentes términos o que incumplan las obligaciones contraídas.</div>

<div className={styles.headingAbout}>MANEJO DE INFORMACIÓN</div>
<div className={styles.pAbout}> La información recolectada por el Proveedor para el registro, es suministrada por los usuario de forma libre y voluntaria, para que esta sea administrada por el Proveedor o por quien éste designe para el cumplimiento de los deberes adquiridos, lo que implica su recolección; almacenamiento en servidores o repositorios del Proveedor o de terceros; circulación de los mismos dentro de la organización del Proveedor; comunicación a los usuarios información comercial, publicitaria y de mercadeo relacionada con su actividad comercial. Así mismo, los datos recolectados serán objeto de análisis para fines de mejorar la estrategia de negocios del portal web, apoyada en herramientas de inteligencia de negocios y minería de datos, que permiten adquirir conocimientos prospectivos para fines de predicción, clasificación y segmentación. El usuario podrá ejercer su derecho de conocer, actualizar, modificar y suprimir los datos personales existentes en las bases de datos asociadas a la Plataforma. Para ello deberá realizar la solicitud de consulta, reclamo o supresión a la dirección electrónica soporte@ggslatam.gg detallando las modificaciones a realizar y aportando los documentos que lo soportan. El Proveedor es responsable del tratamiento de la información personal recolectada a través del portal web, responsabilidad que podrá delegar en un tercero, en calidad de responsable o encargado de la información, asegurando contractualmente adecuado tratamiento de la misma.</div>

<div className={styles.headingAbout}>DOMICILIO Y LEGISLACIÓN APLICABLE</div>
<div className={styles.pAbout}> Los presentes Términos y Condiciones de Uso de La Plataforma se acogen en el territorio Colombiano, conforme a su normatividad general y sectorial. Su adopción implica el ejercicio de su libre voluntad y que la relación que surge de este documento se regirá en todos sus efectos por su contenido y en su defecto por la ley comercial colombiana.</div>

<div className={styles.headingAbout}>ACEPTACIÓN TOTAL DE LOS TÉRMINOS</div>
<div className={styles.pAbout}> El usuario manifiesta expresamente tener capacidad legal para usar La Plataforma. Así mismo, manifiesta haber suministrado información real, veraz y fidedigna; por ende de forma expresa e inequívoca declara que ha leído, que entiende y que acepta la totalidad de las situaciones reguladas en el presente escrito de Términos y Condiciones de Uso de la Plataforma, por lo que se compromete al cumplimiento total de los deberes, obligaciones, acciones y omisiones aquí expresadas.</div>
      </div>
      <Footer />
      </div>
    )
}